## Import Data

In [1]:
import pandas as pd
email_df = pd.read_csv("emails.csv")

In [2]:
email_df.shape

(5728, 2)

In [3]:
email_df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
email_df.loc[0].text

"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  ma

## TF-IDF

In [68]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [69]:
corpus=[]
for i in range(0,5728):
  # remove not alpha characters such as comma, , ;, :  --- , " ...
  review1=re.sub('[^a-zA-Z]',' ',email_df.text.iloc[i])
  # lowercase all charater
  review1=review1.lower()
  # create a list of word
  review1=review1.split()
  # root form of word
  ps=PorterStemmer()
  review1=[ps.stem(word) for word in review1 if not word in set(stopwords.words('english'))]
  review1=' '.join(review1)
  corpus.append(review1)

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_df = 0.7, min_df = 10, ngram_range=(1,2))
# input the list of corpus
x = vectorizer.fit_transform(corpus)

In [74]:
x

<5728x11366 sparse matrix of type '<class 'numpy.float64'>'
	with 595330 stored elements in Compressed Sparse Row format>

In [76]:
x.shape

(5728, 11366)

In [78]:
y = email_df.iloc[:,1].values

In [84]:
len(corpus[0].split())

113

NameError: name 'x_train' is not defined

## Slit train and test



In [86]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [87]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(solver='lbfgs')
classifier.fit(x_train,y_train)

LogisticRegression()

In [88]:
y_pred = classifier.predict(x_test)

In [89]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [90]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [91]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

array([[1292,    9],
       [  21,  397]])

In [92]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(x_train, y_train)

MultinomialNB()

In [93]:
y_pred = clf.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[1299,    2],
       [  49,  369]])

In [95]:
acc = (1299+369)/(1299+369+49+2)
acc

0.9703315881326352

In [97]:
acc = (1292+397)/(1292+397+9+21)
acc

0.9825479930191972